name: Update GitHub Stats

on:
  schedule:
    - cron: "0 */6 * * *"   # runs every 12 hours
  workflow_dispatch:         # lets you run manually from GitHub Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Generate GitHub Stats
        uses: anuraghazra/github-readme-stats@latest
        with:
          token: ${{ secrets.MY_OCTO }}
